---
- name: Install prerequisites for Apache Spark
  hosts: all
  become: true

  tasks:
    - name: Install Java
      apt:
        name: openjdk-11-jdk
        state: present
        update_cache: true

    - name: Install Python
      apt:
        name: python3
        state: present
        update_cache: true

